WITH source(faculty_name, department_name) AS (
  VALUES
    ('Faculty of Allied Health Sciences', 'Department of Audiology'),
    ('Faculty of Allied Health Sciences', 'Lahore School of Nursing'),
    ('Faculty of Allied Health Sciences', 'Department of Rehabilitation Sciences'),
    ('Faculty of Allied Health Sciences', 'University Institute of Physical Therapy'),
    ('Faculty of Allied Health Sciences', 'University Institute of Public Health'),
    ('Faculty of Allied Health Sciences', 'University Institute of Radiological Sciences & Medical Imaging'),
    ('Faculty of Allied Health Sciences', 'University Institute of Food Science & Technology'),
    ('Faculty of Allied Health Sciences', 'University Institute of Diet & Nutritional Sciences'),
    ('Faculty of Allied Health Sciences', 'University Institute of Medical Lab Technology'),
    ('Faculty of Allied Health Sciences', 'Department of Health Professional Technologies'),
    ('Faculty of Allied Health Sciences', 'Department of Optometry & Vision Science'),
    ('Faculty of Allied Health Sciences', 'Department of Emerging Allied Health Technologies'),
    ('Faculty of Arts and Architecture', 'School of Creative Arts'),
    ('Faculty of Arts and Architecture', 'School of Fashion and Textile'),
    ('Faculty of Engineering & Technology', 'Department of Technology'),
    ('Faculty of Engineering & Technology', 'Department of Electrical Engineering'),
    ('Faculty of Engineering & Technology', 'Department of Mechanical Engineering'),
    ('Faculty of Engineering & Technology', 'Department of Civil Engineering'),
    ('Faculty of Information Technology', 'Department of Computer Sciences & IT'),
    ('Faculty of Information Technology', 'Department of Software Engineering'),
    ('Faculty of Information Technology', 'Department of Intelligent Systems'),
    ('Faculty of Languages & Literature', 'Deptartment of English Language and Literature'),
    ('Faculty of Languages & Literature', 'Department of Urdu'),
    ('Faculty of Law', 'M.A Raoof College of Law'),
    ('Faculty of Management Sciences', 'Department of Sports Sciences'),
    ('Faculty of Management Sciences', 'Lahore School of Aviation'),
    ('Faculty of Management Sciences', 'Lahore Business School'),
    ('Faculty of Management Sciences', 'Department of Economics'),
    ('Faculty of Management Sciences', 'Department of Information Management'),
    ('Faculty of Medicine & Dentistry', 'Department of Medical Education'),
    ('Faculty of Medicine & Dentistry', 'Center for Heath Professional Develoment & Lifelong Learning'),
    ('Faculty of Medicine & Dentistry', 'University College of Medicine'),
    ('Faculty of Pharmacy', 'Department of Pharmacy'),
    ('Faculty of Sciences', 'Institute of Molecular Biology & Biotechnology'),
    ('Faculty of Sciences', 'Department of Environmental Sciences'),
    ('Faculty of Sciences', 'Department of Mathematics and Statistics'),
    ('Faculty of Sciences', 'Department of Physics'),
    ('Faculty of Sciences', 'Center for Research in Molecular Medicine'),
    ('Faculty of Sciences', 'Department of Chemistry'),
    ('Faculty of Sciences', 'School of Pain & Regenrative Medicine'),
    ('Faculty of Social Sciences', 'Department of Islamic Studies'),
    ('Faculty of Social Sciences', 'Department of Education'),
    ('Faculty of Social Sciences', 'School of Integrated Social Science'),
    ('Faculty of Social Sciences', 'Lahore School of Behavioural Sciences'),
    ('Faculty of Social Sciences', 'Department of Criminology'),
    ('Faculty of Social Sciences', 'Department of Sociology')
)
INSERT INTO departments (faculty_id, name, is_active)
SELECT f.id, s.department_name, TRUE
FROM source s
INNER JOIN faculties f ON f.name = s.faculty_name
ON CONFLICT (faculty_id, name) DO NOTHING;
